---
- name: run docker-compose on localhost
  hosts: 172.31.8.171
  gather_facts: false
  become: true
  any_errors_fatal: true

  tasks:
  - name: copy config files from ansible node to target node
    run_once: yes
    copy: src=/home/ansiadmin/docker-compose.yml dest=/home/ansiadmin/ flat=yes
