---
- name: run docker-compose on localhost
  hosts: all
  become: yes

  tasks:
  - name: block for ELK Stack and this block is rescued with mail notification
    block:
    - name: run the functional tests written in python script (PUT)
      command: python3 ab-func-tests.py
      register: output
      failed_when: '"errorELKFunctional" in output.stdout'
      when: inventory_hostname == 'localhost'
  
    - name: run the load tests written in python script
      command: python3 ab-load-tests.py  --es_address localhost --indices 4 --documents 5 --seconds 120 --clients 5
      register: output
      failed_when: '"errorELK" in output.stdout'
      when: inventory_hostname == 'localhost'

    rescue:
    - name: when any of tasks fail, mail notification
      debug:
        msg: "notifying the users for failed tasks"
    - name: end the play
      meta: end_play
