---
- name: run docker-compose on localhost
  hosts: all
  become: true

  tasks:
  - name: block for ELK Stack and this block is rescued with mail notification
    block:
    - name: stop current running containers
      shell: "docker stop $(docker ps -aq)"
      ignore_errors: yes

    - name: remove all docker containers
      shell: "docker rm $(docker ps -aq)"
      ignore_errors: yes

    - name: remove all docker images
      shell: "docker rmi $(docker images -q)"
      ignore_errors: yes
  
    - name: stop the docker service
      service:
        name: docker
        state: stopped

    - name: remove the docker packages
      yum:
       name: "{{ packages }}"
       state: absent
      vars:
        packages: 
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-engine

    - name: install docker again
      yum:
       name: "{{ packages }}"
       state: latest
       enablerepo: "amzn2extra-docker"
      vars:
        packages: 
        - docker
  
    - name: start the docker service
      service:
        name: docker
        state: started

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: install elasticsearch python library
      pip:
        name: elasticsearch
      when: inventory_hostname == 'localhost'

    - name: Run containers from docker-compose file from jenkins build
      docker_compose:
        project_src: docker-compose.yml
        executable: pip3
  
    - name: run the functional tests written in python script
      command: python3 ab-tests.py  --es_address localhost --indices 4 --documents 5 --seconds 120 --not-green --clients 5
      register: output
      failed_when: '"errorELK" in output.stdout'

    rescue:
    - name: when any of tasks fail, mail notification
      debug:
        msg: "notifying the users for failed tasks"
    - name: end the play
      meta: end_play
