---
- name: run docker-compose on localhost
  hosts: all
  become: true

  tasks:
  - name: stop current running Running containers
    command: docker stop $(docker ps -aq)
    ignore_errors: yes

  - name: remove all docker containers
    command: docker rm $(docker ps -aq)
    ignore_errors: yes

  - name: remove all docker images
    command: docker rmi $(docker images -q)
    ignore_errors: yes

  - name: remove docker from the targets
    command: yum remove -y docker docker-common docker-selinux docker-engine docker-ce docker-ce-cli

  - name: install docker again
    command: yum install -y docker
